version: "2.4"

services:
  modbus_app:
    image: 'modbustest-modbus_app:latest'
    container_name: modbus_app
    restart: always
    mem_limit: 55m
    mem_reservation: 50m
    volumes:
      - ./cfg-data:/cfg-data