FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY MBMain.py .
COPY MBReading.py .
COPY MQTTOut.py .
COPY settings.py .
COPY Param.JSON .

CMD ["python", "MBMain.py"]