FROM python:3.11-slim


RUN apt-get update 
RUN apt-get install -y apt-utils
RUN apt-get install -y gcc

COPY ./ ./app/
WORKDIR /app/
RUN pip install -r requirements.txt


# build executable
CMD ["python3","-u", "./MBMain.py"]